name: Build and deploy Storybook

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy public guide
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          check-latest: true
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Storybook
        run: npm run build-storybook
      - name: Upload pull request preview artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: storybook-static
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: Cecilapp/GitHub-Pages-deploy@3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: thomas.rosen@me.com
          build_dir: storybook-static
          cname: "design.volt.link"
          branch: deploy_frontend
